// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A flow to generate a title for a conversation.
 *
 * - generateConversationTitle - A function that generates a conversation title.
 * - GenerateConversationTitleInput - The input type for the generateConversationTitle function.
 * - GenerateConversationTitleOutput - The return type for the generateConversationTitle function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateConversationTitleInputSchema = z.object({
  conversationHistory: z
    .string()
    .describe('The complete history of the conversation.'),
});
export type GenerateConversationTitleInput = z.infer<
  typeof GenerateConversationTitleInputSchema
>;

const GenerateConversationTitleOutputSchema = z.object({
  title: z.string().describe('The generated title for the conversation.'),
});
export type GenerateConversationTitleOutput = z.infer<
  typeof GenerateConversationTitleOutputSchema
>;

export async function generateConversationTitle(
  input: GenerateConversationTitleInput
): Promise<GenerateConversationTitleOutput> {
  return generateConversationTitleFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateConversationTitlePrompt',
  input: {schema: GenerateConversationTitleInputSchema},
  output: {schema: GenerateConversationTitleOutputSchema},
  prompt: `You are an expert at generating concise and descriptive titles for conversations.
  Given the following conversation history, generate a title that accurately reflects the main topic of the conversation.
  The title should be no more than 10 words.

  Conversation History: {{{conversationHistory}}}
  `,
});

const generateConversationTitleFlow = ai.defineFlow(
  {
    name: 'generateConversationTitleFlow',
    inputSchema: GenerateConversationTitleInputSchema,
    outputSchema: GenerateConversationTitleOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
