// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A flow to generate a title for a conversation.
 *
 * - generateConversationTitle - A function that generates a conversation title.
 * - GenerateConversationTitleInput - The input type for the generateConversationTitle function.
 * - GenerateConversationTitleOutput - The return type for the generateConversationTitle function.
 */

// Mock implementation for generating conversation titles
export async function generateConversationTitle({
  conversationHistory,
}: {
  conversationHistory: string;
}) {
  return { title: `Mock title for: ${conversationHistory}` };
}
